#circle (a=r2*3.1416)
print('To calculate the area of the circle add the following data')
num1=int(input('radio: '))
areac=(num1*num1*3.1416)
print('  The area of the circle is:', areac)

#trapezoid (a=AUT+ALT)
print('To calculate the area of the trapezoid add the following data')
num1=int(input('Area of the upper triangle:'))
num2=int(input('Area of the lower triangle: '))
areat=(num1+num2)
print(' The area of the trapezoid is:',areat)

#rhombus (a=D*d/2)
print('To calculate the area of the rhombus add the following data')
num1=int(input('Major diagonal: '))
num2=int(input('Minor diagonal: '))
arear=(num1*num2/2)
print(' The area of the rhombus is:', arear)

